server.port=8083
spring.application.name=test-product-service

management.server.port=9083
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=info,health
management.endpoint.health.show-details=ALWAYS
management.endpoints.web.path-mapping.health=/healthcheck